export enum Routes {
  LANDING = '/',
  SIGN_UP = '/signup',
  SIGN_IN = '/login',
  HOME = '/home',
  ACCOUNT = '/account',
  ADMIN = '/admin',
  PASSWORD_FORGET = '/forgot-password',
  // tracks
  SPA = 'tracks/spa',
  LEMANS = 'tracks/lemans',
  SHANGHAI = 'tracks/shanghai',
  WATKINS = 'tracks/watkins-glen',
  SEBRING = 'tracks/sebring',
  BATHURST = 'tracks/bathurst',
  ZOLDER = 'tracks/zolder',
  DAYTONA = 'tracks/daytona',
  BARCELONA = '/tracks/barcelona',
  ROADAMERICA = 'tracks/road-america',
  SILVERSTONE = 'tracks/silverstone',
  LAGUNA = 'tracks/laguna-seca',
  MUGELLO = 'tracks/mugello',
  ZANDVOORT = 'tracks/zandvoort',
  NURBURGRING = 'tracks/nurburgring',
  MAGIONE = 'tracks/magione',
  VALLELUNGA = 'tracks/vallelunga',
  ROADATLANTA = 'tracks/road-atlanta',
  MOSPORT = 'tracks/mosport',
  SUZUKA = 'tracks/suzuka',
  BAHRAIN = 'tracks/bahrain',
  FUJI = 'tracks/fuji',
}
